apiVersion: apps/v1
kind: Deployment
metadata:
  name: urlshortener
spec:
  replicas: 3
  selector:
    matchLabels:
      app: urlshortener
  template:
    metadata:
      labels:
        app: urlshortener
    spec:
      containers:
        - name: urlshortener
          image: urlshortener:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_DATASOURCE_URL
              value: jdbc:postgresql://postgres:5432/urlshortener
            - name: SPRING_DATASOURCE_USERNAME
              value: shortener
            - name: SPRING_DATASOURCE_PASSWORD
              value: shortener
            - name: SPRING_DATA_REDIS_HOST
              value: redis
            - name: SPRING_DATA_REDIS_PORT
              value: "6379"
